package com.dicoding.picodiploma.loginwithanimation.utils

const val WEIGHT_RESULT = "WEIGHT_RESULT"
const val FACE_DETECTION = "FACE_DETECTION"
const val DOKTER_APPOINMENT = "DOKTER_APPOINMENT"
const val PHOTO_APPOINMENT = "PHOTO_APPOINMENT"
const val LABEL_APPOINMENT = "LABEL_APPOINMENT"
const val DATE_APPOINMENT = "DATE_APPOINMENT"
const val TIME_APPOINMENT = "TIME_APPOINMENT"